### ISSUE TITLE
Markdown styling for blogs

### ISSUE THREAD

**Issue by pferrel** [actionml/blog.actioml.com#3]
I've put an example of what we need styled for markdown at http://dev.actionml.com/blogs/md_test

Lots of missing things missing here but I assume it's because the styling is incomplete.

**Comment by pferrel** [comment]
Why is this closed, even parsed elements are not styled correctly

**Comment by pferrel** [comment]
page is actually here: http://dev.actionml.com/blog/md_test

I'll update to remove things not supported by the parser

**Comment by pote** [comment]
Please direct all issues to the github.com/actionml/actionml.com repo.
